### ISSUE TITLE
Have scannable QR Code on Receive View similar to Monero-Core

### ISSUE THREAD

**Issue by dternyak** [mymonero/mymonero-app-js#107] opened 2017-05-20 21:56 UTC
Currently, there is no way scan another user's mobile device to pay them. Instead, one must send a receive request via email/txt/etc.

A possible version of the design could be a QR Code that would be visible at the Receive view, above the listview of receive items.

Later, additional information (like amount) could be embedded in the QR if it relates to a specific receive request, and that QR Code would be visible at the request detail view.

This feature would be especially useful in combination with https://github.com/mymonero/mymonero-app-js/issues/21

**Comment by dternyak** [comment] 2017-05-20 22:04
@mds - @paulshapiro Said it would be good to get your design input for this.

**Comment by mds** [comment] 2017-05-21 00:03
Hey there, I'm not sure what kind of design input to give, but scanning someone else's phone to pay them sounds like a good feature to me for those in-person interactions. My hunch would be that that would be a much lower use case though.

**Comment by snaggen** [comment] 2017-05-21 05:33
It is useful for letting someone in a small shop/cafe to start accepting monero. It can be used as a poor man's point of sale.

**Comment by dternyak** [comment] 2017-05-21 05:42
@mds Additionally, in-person exchanges, e.g. payback for buying dinner.

I think @paulshapiro was hoping you might have time to implement an actual mockup, but I'm not sure what the arrangement is there so I can only stress *hope* :)

**Comment by dternyak** [comment] 2017-05-21 05:45
@mds This is how copay, one of the largest bitcoin wallets, does it:

https://lh3.googleusercontent.com/Jxl7ooxkmBUNBnPj98AIWgAQu3R1jxj1ovqG4wZ-aQVU00-FDrq5U0ZYJKkGZE2oviFh

**Comment by tficharmers** [comment] 2017-05-21 06:09
I agree that this would be a useful feature.

I also think there will be instances where someone will request (or want to send) some xmr based on a fiat value eg: "I'll pay you that $22 in Monero. Hang on, I just need to use another app to work out the exchange rate." In the current app there is no way to work this.

I am already thinking about this feature. I will create an issue for it and will cross-link after I've created it.

**Comment by snaggen** [comment] 2017-05-21 11:19
I agree with @tficharmers that this feature should be combinded with #108. 
I'll add some more Copay screenshots, to show how they handle the "Request a specific amount" part also. 
1. The initial Recieve screen with the QR-code for the adress only. 
![screenshot_20170521-140415](https://cloud.githubusercontent.com/assets/6420639/26283392/6165dc1e-3e30-11e7-8533-9567144ba0e9.png)

2. When you click on "Request a specific amount" you get to enter the amount in the preferred fiat currency, or BTC. You click on the currency button to switch between them.

![screenshot_20170521-140431](https://cloud.githubusercontent.com/assets/6420639/26283394/69fb436e-3e30-11e7-81b6-04cad8479db8.png)

3. When you have entered the amount and clicks the green arrow button, you get to the new recieve screen for the custom amount

![screenshot_20170521-140446](https://cloud.githubusercontent.com/assets/6420639/26283398/6fd4ced6-3e30-11e7-83c3-af0f291d63d1.png)

**Comment by paulshapiro** [comment] 2017-05-21 18:01
Hey everyone,

Thanks for sharing all of your thoughts and the screenshots. Very helpful. I can definitely see how this would improve payments UX, primarily on mobile. I'm going to take all of this into consideration and do a deeper dive when I free up. But I also agree that this is connected to a few other things, so it'll probably appear in full form only in a near future version. Not clear to me if it's worth delaying the initial Android release til we have everything we would need to emphasize QR scanning, such as QR code scanning via camera from Send Funds, which has been put on hold until I can get my hands on a more recent Android device to develop/test it on. 

If you have any continued thoughts or suggestions, keep 'em comin'! :) 👍 

Paul

**Comment by paulshapiro** [comment] 2017-09-10 15:45
@snaggen @tficharmers @mds 

Alrighty! I've gone ahead and done a few things in the app after a good bit of investigation of options. I came to the conclusion it made the most sense to fit the capability to show a QR code for a given wallet into the existing Requests system. The main reasons are that not doing so would end up having us basically reproduce the Requests system within the Wallets tab, and because displaying a scannable QR code for a wallet is something we'd want to do for all Requests, too. So here's what I did…

* Amounts are now optional in Requests, making it possible to create a Request without needing to do anything but select a 'from' wallet - which is already selected by default

* I added "Send From" and "Receive At" action buttons on the Wallet details page, making it possible to simply tap the Receive button to create a request to view the QR code for that wallet

* I enhanced the Request details page to show a larger QR thumb above the Request URI, which has been made clickable. Upon click, a new "Scan to Pay" view is presented as a modal with a zoomed-in version of the QR code and an informational label telling the payer (who will be scanning the QR code) about the Request they're scanning (i.e. "Scan to send N XMR to 4XXXXXX…"). The idea behind this is to serve as a scannable bill to be shown, e.g. to a customer at a cafe.

This kind of system is more powerful/featureful than only being able to show the QR code for a wallet, but it does have the trade-off that it involves a couple more taps. Now that we have this system, there's the possibility that there's a good design solution to showing the QR code for a wallet with only a single tap, but I'm not aware of one yet. The issue, as mentioned, is about where to draw the line in how much functionality is exposed in the Wallets tab for QR display (especially since we're talking about features like specifying a dollar amount in the Request).

Please give it a whirl (it's on master) and let me know what you think. I think it works pretty well as the initial step, but am sure it can stand to be improved and will be happy to integrate any suggestions. 

–Paul

P.S. I did certainly consider options like spawning a Request form from the Wallets tab, as well as showing an auto-recalculated scannable QR code on the Requests form - in order to function similarly to the above screenshots - but as mentioned I opted for the solution above after investigation.

P.P.S. We are definitely looking at currency agnosticism, generating Requests by pegging to other currencies, and (related) showing wallets balances and Send amounts in currencies of choice - but that will be handled as a separate issue (https://github.com/mymonero/mymonero-app-js/issues/108)

**Closed by paulshapiro** 2017-09-10 15:45 UTC
Labels: (may) need server work, blocking android launch, blocking desktop launch, feature / enhancement, feature idea, feature request
