### ISSUE TITLE
Can't spend coinbase txs

### ISSUE THREAD

**Issue by moneroexamples** [mymonero/mymonero-app-js#240] opened 2018-10-25 06:26 UTC
I have stagenet wallet (seed below) which has  only few coinbase txs (no other txs present). I can't spend anything from this wallet. The mymonero-app-js constructs txs and submits it to daemon, but demon rejects it with the message:

```
2018-10-25 06:07:34.847	[RPC0]	WARN 	daemon.rpc	src/rpc/core_rpc_server.cpp:728	[on_send_raw_tx]: tx verification failed: invalid input
```

Not really sure if this is problem with mymonero-app-js, but before I started testing it with openmonero's backend, I could spend coninbase txs. Thus I think that this is some problem with mymonero-app-js and its new codebase. 

Would you mind checking if you can spend coinbase txs? 

Stagenet wallet seed:
```
peaches purged gossip either gyrate organs asked ability autumn inexact coffee rays avidly fountain foxes wrist goldfish masterful anecdote sulking masterful science beyond coffee coffee
```

**Comment by paulshapiro** [comment] 2018-10-25 16:19
Yes, thanks for the seed info, I'll look at this asap

**Comment by moneroexamples** [comment] 2018-11-01 03:10
Hi. Just wondering whether you had a chance to look at the issue?

**Comment by paulshapiro** [comment] 2018-11-01 03:39
Finally coming up on my list. Been swamped. Normally woulda looked at it but had some other items. Estimate ~couple days

**Comment by moneroexamples** [comment] 2018-11-01 04:28
No problem. Thanks for the update.

**Comment by paulshapiro** [comment] 2018-11-02 01:44
@moneroexamples do you have a stagenet openmonero instance I could point my app to?

**Comment by moneroexamples** [comment] 2018-11-02 02:07
This is my stagenet explorer: http://139.162.60.17:8082/

You can try connecting to this node: 139.162.60.17, or monerojo wallet nodes: stagenet.monerujo.io or stagenet.xmr-tw.org

**Comment by paulshapiro** [comment] 2018-11-02 02:16
Didn't realize you also have a stagenet instance open at http://172.104.45.209:81 -- but login didn't work for me (even under http -- timed out)... any info about that? Just thought it would be good to get some openmonero testing in while I could :) Thanks for the stagenet node info

**Comment by paulshapiro** [comment] 2018-11-02 02:28
hm unsure why CORS would need disabling but yeah, I plan to add a (at least debug mode or authenticated) Preferences toggle to disable https, and a dropdown for nettype.

**Comment by paulshapiro** [comment] 2018-11-02 02:30
hmm i get 404 on `/login`

**Comment by paulshapiro** [comment] 2018-11-02 20:29
I can login through the browser and see the JSON API requests to the same server, so, still digging into what's going on.

**Comment by paulshapiro** [comment] 2018-11-02 20:43
Can be repro'd with `curl 'http://139.162.60.17:81/login' -H 'Content-Type: application/json' -H 'Accept: application/json' -d '{"address":"56bY2v2RJZNEvrKdYuwG73Q2idshQyGc5fV74BZqoVv72MPSBEakPbfWYtQH4PLGhk3uaCjNZ81XJ7o9pimAXzQFCv7bxxf","view_key":"9ef8e116d2c774b207a2dd6a234dab8f5d54becc04aa26ccbd6f1f67e8427308","create_account":true}'`

**Comment by paulshapiro** [comment] 2018-11-02 20:43
Oh the API port is 1984 😅

**Comment by paulshapiro** [comment] 2018-11-02 21:08
Submitted a few and reproduced (stagenet + OpenMonero + MyMonero desktop with zero errors btw! ^5) 

Does the daemon happen to log "tx used wrong inputs, rejected" in level 1 mode when it occurs?

Still digging

**Comment by moneroexamples** [comment] 2018-11-02 23:42
Yes, bunch of invalid input errors: https://i.imgur.com/MQSc4cK.png

But do you get the same problem with MyMonero's backend? As for now I understand that you have checked with openmonero?

**Comment by paulshapiro** [comment] 2018-11-02 23:58
Just wondering if it happens to log that specific string "tx used wrong…" given some code diving from earlier. 

We're not seeing these errors on MyMonero prod / mainnet. Only things like recent "invalid output" (not input) rejections, which we're now diagnosing and have gotten a few support requests about. 

I'm working on spinning up a stagenet mymonero image while having gotten core-cpp working with the specific tx construction inputs as are generated for the sample stagenet wallet to step through.

**Comment by moneroexamples** [comment] 2018-11-03 00:11
I think its only related to coinbase txs and when you spend them. On mainnet I think you will not find much coinbase-only wallets. I can also prepare testnet wallet with coinbase-only txs, if testnet would be easier to use for you with your backend? 

Coinbase txs require special treatment on the backend, when preparing `rct` field for `random_output`. MyMonero API docs dont specify how coinbase txs are handled: https://github.com/monero-project/meta/blob/b6e64701ced97cc28545c7b296914209e10fec52/api/mymonero_rest.md  Thus previously I was doing this this way in openmonero: https://github.com/moneroexamples/openmonero/blob/mymonero_v9/src/YourMoneroRequests.cpp#L680 

But now this does not work. Thus the question is what has changed? Is it something on the mymonero v9 code? Or openmonero backend should be modified how it treats coinbase txs? 

So for now, I would like to clarify with you if you also have this issue on your backend with coinbase txs, either on stagenet or testnet.

**Comment by moneroexamples** [comment] 2018-11-03 00:38
Thanks. I will also try investigate this more, but its difficult to figure out how should they be treated currently. Thus clarification in the api, some example, or information what response and how does your back-end prepares `rpc` fields for coinbase txs would be most helpful.

**Comment by paulshapiro** [comment] 2018-11-03 02:15
> Coinbase txs require special treatment on the backend, when preparing rct field for `random_output`. 

Just want to confirm you mean `get_unspent_outs` here

Anyway, pretty sure I know what's going on here. The MM server serves no `rct` key-value for coinbase unspent outs. The client (current core-cpp going back to old cn_util.js), in the case of a nil `rct` field, fills in by generating a commit to the (already publicly known) `output.amount` and the identity for the mask. OpenMonero in this case is providing a constructed rct field, so the client is getting confused and must be generating the wrong mask because it thinks it must decrypt one. Does it sounds like it makes sense for OM to remove the field value for such coinbase outputs?

**Comment by moneroexamples** [comment] 2018-11-03 03:46
`get_unspent_outs`, yes.

> Does it sounds like it makes sense for OM to remove the field value for such coinbase outputs?

I will check that soon, and report back. Thanks for this.

**Comment by paulshapiro** [comment] 2018-11-05 22:08
Notification for this got buried in inbox. That is quite a smart fix, as far as I can tell, although, isn't there a vanishing chance that we could get an encrypted mask that looks like the identity mask. (If your fix is sufficient though, I need to reconfirm what we're doing on our server)

**Comment by moneroexamples** [comment] 2018-11-06 01:04
If you look at monero's `light_wallet_get_unspent_outs`, it assigns identity mask to ringct coinbase tx: 
https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.cpp#L7976 If its non-coinbase ringct, then mask is being decrypted.

To not relay on the identity mask for coinbase output obtained from a backend, one would have to send a flag to the frontend indicating that this output is coinbase so that it can be treated as a special case. This would require modification of an api.

This is my-understanding on what was happening with coinbase txs that they could not be spend.

**Comment by paulshapiro** [comment] 2018-11-06 01:13
> one would have to send a flag to the frontend indicating that this output is coinbase so that it can be treated as a special case. This would require modification of an api.

Agreed

> If you look at monero's light_wallet_get_unspent_outs, it assigns identity mask to ringct coinbase tx:

Oh, totally. I'm just saying, from the lightweight wallet client's perspective, it sounds like it's trying to assume the following statement is true: no encrypted mask will look like the plaintext identity mask. Just not sure if that's the case.

**Comment by paulshapiro** [comment] 2018-11-06 01:35
> But probably the easiest way would be to just send flag in get_unspent_outs which output is coinbase or not.

Agreed. Just doing last minute checks we're not missing anything.

**Comment by luigi1111** [comment] 2018-11-06 02:11
I'm of the opinion that no additional handling beyond "is mask identity" is necessary. The failure mode is a cryptographically negligible possibility that isn't even catastrophic really.

**Comment by luigi1111** [comment] 2018-11-06 02:36
If we're adding a new flag, I think technically is_rct is the correct one. Then if you get an output with is_rct set but rct field is blank, you know to regen with identity. I think pre-rct coinbase outs might fail with just is_coinbase unless you put the values in rct anyway, which means the flag would be kinda pointless and could be replaced with a helpful comment on how to use the rct field. :)

**Comment by moneroexamples** [comment] 2018-11-06 02:47
I'm good either way as well. Which ever the way will be chosen, I think https://github.com/monero-project/meta/pull/272  and https://github.com/monero-project/meta/blob/b6e64701ced97cc28545c7b296914209e10fec52/api/mymonero_rest.md should be updated, to reflect that.

**Comment by luigi1111** [comment] 2018-11-06 03:34
> To confirm, by "how to use the rct field",

Correct, though it doesn't necessarily need to be an identity mask. It could be all 0s or anything that would be obviously "wrong" for normal use. It could even be "coinbase" if that doesn't obviously break existing functionality (causing upgrade pains).

Basically RCT coinbase outs use public everything, so all passed values in the rct field are completely unnecessary technically.

The main thing is that it is marked as a v2 ("rct") coinbase for purposes of zeroing the input amount and getting RCT mix partners (I know this is reiterating the conversation from before, but for succinctness...).

**Comment by paulshapiro** [comment] 2018-11-06 16:29
Ok, thanks for the confirmation. Given there's an 'obviously wrong' value, I favor the option of not including a `is_rct`, as the existence of the `rct` field can remain the indicator of `is_rct`. Will follow up and propose something like this to the standard.

**Comment by paulshapiro** [comment] 2018-11-06 18:13
Ok so final word on this from our side is we'll have the server rewrite the `rct` field for coinbase rct in the way OpenMonero is doing, and will make the related change to core-cpp to support it. We'll add this to the meta repo doc.

**Comment by paulshapiro** [comment] 2018-11-06 20:16
https://github.com/mymonero/mymonero-core-cpp/commit/13b943d5803c83cedc10a1ad7f35492f2916d780

**Comment by vtnerd** [comment] 2018-11-06 20:20
One proposal I would make is to _eventually_ change the `rct` field (or a new field to distinguish) to contain just the unencrypted mask. That should be the only portion needed by the frontend. The commitment is computed from the mask and amount (which is sent already). For coinbase transactions this would be the identity value.

This would require some re-working on the frontend, so perhaps its not worth it. The open source server pending in PR stores only the mask, and re-computes the other two values on-the-fly when requested via the API. The encryption to mask and amount can even be duplicated via the ECDH value.

**Comment by paulshapiro** [comment] 2018-11-07 14:42
Sounds good to me. Perhaps we can do this when we (version the API in order to?) condense the endpoints and remove other redundant data.

**Closed as completed** 2018-12-20 15:25 UTC
