### ISSUE TITLE
Android: Application expands onto status bar section

### ISSUE THREAD

**Issue by shuannelson** [mymonero/mymonero-app-js#90] opened 2017-05-07 18:40 UTC
On Android, the application extends onto the statusbar and makes it hard to press buttons at the top of the screen. This appears to be an issue on only some android devices, as Endogenic has not been able to reproduce.

Issue was experienced on Android 25 (7.1.1.) on Nexus 5X. 

A margin-top, selectively when the app does expand onto the statusbar, is likely the fix. 

See below for an example.

<img width="379" alt="screen shot 2017-05-03 at 11 03 25 pm" src="https://cloud.githubusercontent.com/assets/28512379/25783956/79373952-332a-11e7-86a7-fb145f15d398.png">

**Comment by paulshapiro** [comment] 2017-05-08 18:00
Is anyone else seeing this?

**Comment by rdamen** [comment] 2017-05-12 22:33
Yes, I'm seeing this on 7.1.2 as well.

**Comment by paulshapiro** [comment] 2017-05-19 00:16
@rdamen @shuannelson @dternyak 

Could anyone who was seeing this issue check again after pulling the above fix? Unfortunately can't repro but have some reasons to believe the above fixed it.

**Comment by rdamen** [comment] 2017-05-19 01:30
Can confirm fixed on 7.1.2. Thanks!

**Closed** 2017-05-19 01:32 UTC
Labels: blocking android launch, bug

**Comment by paulshapiro** [comment] 2017-05-19 01:34
FWIW this was not caused by the above commit's issue but by lines of code I had added for iOS. https://github.com/mymonero/mymonero-app-js/commit/6ad5c6b21e80bc0a299aa8120b77e9054b436bb8
