### ISSUE TITLE
Windows 10 / Exchange / Error 502

### ISSUE THREAD

**Issue by ErwSim** [mymonero/mymonero-app-js#335] opened 2020-10-17 18:54 UTC
![image](https://user-images.githubusercontent.com/32873009/96351007-1018ff80-10b9-11eb-8f63-51fbc709e962.png)

Got this error the whole day

**Comment by karlbuys** [comment] 2020-10-19 10:07
Hi ErwSim

Thank you for letting us know.

We believe this to be as a result of partner throttling limits and are working towards resolving this problem.

I will let you know once we've managed to address this

**Comment by zdeneksofr** [comment] 2021-02-07 06:22
Same here since yesterday - Mac + iOS (both in latest, app also latest) + also webapp - error 502 while Exchange

**Comment by devinpearson** [comment] 2021-02-08 15:18
Yes, this release went out slightly earlier than the server changes. the alternative exchanges will go live in a few hours.

**Comment by ohhsodead** [comment] 2021-03-01 02:35
still receiving this error..

**Comment by freemelee** [comment] 2021-03-28 17:59
Problem still unsolved by March 28th 2021

**Comment by devinpearson** [comment] 2021-03-28 20:28
We are still looking at improving these error messages. In most cases, it's caused by the exchange amount being too low or a restriction on the region you're accessing it from.

**Comment by devinpearson** [comment] 2021-08-02 10:06
This issue has been resolved. as over v1.1.23 which included improved error handling. If anyone is still receiving these error messages Ill reopen the issue

**Closed by devinpearson** 2021-08-02 10:06 UTC
