### ISSUE TITLE
why I got "invalid mnemonic" ?

### ISSUE THREAD

**Issue by 221V** [mymonero/mymonero-app-js#559] opened 2024-05-27 20:59 UTC
hello

I do not understand why I got and what means "invalid mnemonic" ?
I just try to use words from monero list for new wallet import
https://github.com/monero-project/monero/blob/master/src/mnemonics/english.h

**Comment by karlbuys** [comment] 2024-06-20 09:18
Duplicate of #558

**Closed as completed** 2024-06-20 09:18 UTC
