### ISSUE TITLE
View certain XMR amounts in a Fiat currency denomination of the user's choice

### ISSUE THREAD

**Issue by tficharmers** [mymonero/mymonero-app-js#108] opened 2017-05-21 06:45 UTC
I think it would be a nice feature to be able to view the value of your Monero balance in USD, GBP, etc. There are other areas that this feedback would also be useful, eg:

1. on the main balance
2. when entering how much XMR to send
3. when entering how much XMR to receive when creating a request
4. potentially on wallet previews (on the main MM wallet selection screen)

Here are some interaction ideas for the above:

1. Either a tap/click on the main xmr balance to toggle between the Monero value and the fiat value, or a press and hold/mouse hover to temporarily view the fiat value. Releasing/unhovering switches back.
2. There is space to the right of the Amount box where this could be displayed. Or, there may be instances where the user wants to enter a fiat value in a box and this converts at the exchange rate to the xmr value to send. A more interesting design challenge.
3. Similiar to point 2.
4. Loads of space for this. Just has to be done well.

I am not sure about having it on Transaction history as this could both overly clutter the screen and a tricky decision has to be made on what value to show; the exchange rate confusing at the point of transaction, or the current exchange rate. The latter could be conversing due to price volatility ("Wow! Dinner last night cost a lot"). The former could be confusing as two transactions next to each other of the same XMR amount could have widely different fiat values. So anyway, perhaps leave this implementation for now.

Also, there is a UX consideration if this is added to a Monero Request. I think it should be there when creating a request, but if both the XMR and fiat value exist on a saved request and sent to another user, this could provide confusion based on exchange rate fluctuations. For example, John pays Steve 0.3 xmr for a cinema ticket. Steve bought John's cinema ticket for $10. John sends the request around the time of purchase, but Steve only checks and processes the request two days later. 0.3 xmr might be worth $8 or $12. Steve wonders why he has been under/over charged.

The option to choose your fiat currency of choice would be in the Settings area.

Some things to think about. When I have time, I can mock up some of these ideas, unless someone beats me to it :D

**Comment by tficharmers** [comment] 2017-05-31 14:37
I have attached some designs on how this could be integrated. Nothing ground-breaking, but thought it would help people visualize it.

There are 3 options for the 'Send' screen. I'm not 100% sure which I prefer, but anyway, food for thought. The 'Send' screen implementation could be replicated on the 'Receive' screen as it is similar.

Let me know if this stirs some other ideas and I'll see if I can mock them up.
![fiat features v1](https://cloud.githubusercontent.com/assets/23356013/26637317/10edbcfe-4617-11e7-9a10-af083986679a.png)

**Comment by snaggen** [comment] 2017-06-01 08:07
I'd say the last send screen is to prefer. The other two have multiple input fields, which might give the impression that it would be separate entries and would be added together or something like that. For the last scree, I would make the XMR label a toggle button. When toggled it would change from XMR to USD letting the user enter the amount in USD.

**Comment by tficharmers** [comment] 2017-06-02 08:59
@snaggen Thanks for the feedback. I agree. Perhaps something like this?

![fiat features v1 2](https://cloud.githubusercontent.com/assets/23356013/26718827/31741be4-477a-11e7-823f-e44b38049417.png)

**Comment by tficharmers** [comment] 2017-06-02 09:56
So that would be a dropdown to house several fiat currencies, but thinking about it further and re-reading your comment, perhaps that isn't really a requirement. There could be an option in the Settings to select a single fiat currency of your choice, then like in the main balance, simply tapping/clicking the 'XMR' label would toggle it? This would mirror the behaviour in the main balance strip.

![fiat features v1 4](https://cloud.githubusercontent.com/assets/23356013/26720959/f2d0fe04-4781-11e7-81cb-994596db9976.png)

**Comment by tficharmers** [comment] 2017-06-02 10:08
Here is the same idea but with the toggle on the left.

![fiat features v1 5](https://cloud.githubusercontent.com/assets/23356013/26721455/bf4a581c-4783-11e7-990c-ae6179b47ce3.png)

**Comment by snaggen** [comment] 2017-06-02 10:37
As you say, only toggle between the fiat from the setting and xmr is needed. And I think having the toggle of the right side looks best when text is used, like xmr, usd, eur etcetera. And even when symbols are used, most still are placed after the amount, I guess $ is a little special here.

**Comment by tficharmers** [comment] 2017-06-02 11:30
Of course. Here is option replacing '$' with 'USD'. I think I prefer this for consistency reasons, but just putting the options out there. 

![fiat features v1 6](https://cloud.githubusercontent.com/assets/23356013/26724022/295c2018-478f-11e7-8a94-33b9fe0d3f17.png)

**Comment by snaggen** [comment] 2017-06-02 11:48
@tficharmers that looks great

**Comment by paulshapiro** [comment] 2017-06-02 12:52
@tficharmers This is awesome. Definitely like the direction you're going. I agree as well that default currency should be in Settings. Can probably detect a default by user locale. We'll also probably want to apply this same kind of thing to the Create Request form. I'll have some more input as I look more deeply into the currency exchange integrations we'll be doing.

**Comment by khantahirx** [comment] 2017-08-18 06:54
Can simply fetch it from this json.

https://coinmarketcap-nexuist.rhcloud.com/api/xmr/price

**Comment by paulshapiro** [comment] 2017-10-17 22:19
@tficharmers One quick thing to add about this. In reply to the problem you brought up regarding multiple currencies present on a single Request, we should store only the (singular) currency that the user is selecting when creating the request - then when a mymonero app receives a request URL with a particular specified currency, it will do the conversion at the time of the sender doing the actual Send. We can display the amount from the Request in a label just below the input field from the Amount field on the Send screen, if it's not in the currency the user has selected as their default or current currency.

**Comment by paulshapiro** [comment] 2017-10-17 23:16
@tficharmers

> So … tapping/clicking the 'XMR' label would toggle it between the two?

IMO because right now we only support sending XMR, the amount input field should remain fixed as XMR for now.

**Comment by paulshapiro** [comment] 2017-10-17 23:22
@tficharmers @snaggen do you think it'll ever be a use-case that someone will want to create Requests in arbitrary 'alternate currencies'? because, if we only have this new currency toggle selector next to the Amount field, and a user wanted to create Requests in say 3-4 different currencies, they'd have to go to Preferences and toggle it back and forth to make it happen. Any thoughts? I'm ok saying that's just how it is for now until we have more data on use cases.

But on the other hand, we could just put a new currency dropdown/select element/control in the Create Request form which lets us specify the currency of choice. That fits in with the model of associating a singular explicit currency with each Request. This does seem to make sense the more I turn it over. We can include Monero in that list (which we would obviously not do in the currency dropdown we'd put in Preferences) and, perhaps, if the user has not actually gone into Preferences and explicitly set a value for alternate-currency-of-choice, we just set Monero as the default currency for all new Requests. Else read from the Prefs. 

Thoughts? :)

**Comment by paulshapiro** [comment] 2017-10-18 00:47
So, after speccing this and going through some usage flows, I realized that there's a minor issue with not letting the user select the currency associated with the Amount fields themselves.

The issue is this. Suppose I create a request with the currency USD and amount 100 and send it to @tficharmers, the would-be sender. When he receives the request, his app will take the currency USD and value of 100 and convert it to ~1 XMR. That's how much it would send. Ostensibly, we'd only be able to display either only ~1 XMR in the amount field or display the amount in the sender's 'display in currency'. The problem with doing so is it doesn't give the sender a clear sense of what the **actual content** of the request was and more importantly, exactly how the conversion value was obtained. 

Displaying it as an actual $100 in the Send form would be much clearer to the sender IMO. They'd be expecting that. 

What I'm thinking is, we can actually use the currency toggle button that y'all have been talking about and turn it into a dropdown/select.

Then we can simply display the **actual** Monero amount to be sent in the text label which is to the right of the amount text input and currency selector element. If the user instead selected "XMR" as the currency, we would not display any value in the label to the right of the amount and currency selector element.

Feedback?

**Comment by paulshapiro** [comment] 2017-10-18 02:05
irc user unknownids shares the app Mist with a nearly equivalent concept https://i.stack.imgur.com/1AwLT.png

**Comment by tficharmers** [comment] 2017-10-18 09:55
@paulshapiro Yes, after the usage flows you mentioned, I think the fiat currency selector next to the input field would be better. There is a toggle design in one of the earlier designs if Matt has done one already.

And yes, I think your explanation for Requests makes sense :)

**Comment by tficharmers** [comment] 2017-11-13 11:39
I've just checked out the `displayCurrency` branch and think the implementation is nice. It's slightly different to what I suggested, but I think you've simplified it for the better.

The only thing I would say is I wonder if the currency dropdown on the Send & Request pages, needs an arrow like it appears on the Settings page? Honestly, it took me a few minutes to click it ;-)

**Comment by paulshapiro** [comment] 2017-11-14 18:46
> an arrow like it appears on the Settings page

@tficharmers Yes I pondered that. I think you're right. I do think it may need to be subtle enough not to visually busy the area but should be able to be easily picked out when the element is focused upon. 

FYI I've merged the branch to `develop` now for simplicity.

**Comment by paulshapiro** [comment] 2017-11-14 19:00
For simplicity I'm going to close out this issue and open a new one with @tficharmers specific feedback about the `displayCurrency` branch. Anyone at all who has any feedback is very welcome to submit additional such issues or let me know via IRC et al.

**Closed by paulshapiro** 2017-11-14 19:00 UTC
Labels: feature / enhancement
